/**
 * Agent Skills Generator
 * Produces SKILL.md files compatible with Claude Code, Codex, Cursor, Gemini CLI.
 */

export interface SkillInput {
  name: string
  role: string
  purpose: string
  instructions: string
  tools: string[]
  workflow: string
  examples: string
  constraints: string
  target: 'CLAUDE_CODE' | 'CODEX' | 'CURSOR' | 'GEMINI_CLI' | 'ALL'
}

export function generateSkill(input: SkillInput): { markdown: string; json: object } {
  const targetMap: Record<SkillInput['target'], string> = {
    CLAUDE_CODE: 'Claude Code',
    CODEX:       'Codex CLI',
    CURSOR:      'Cursor',
    GEMINI_CLI:  'Gemini CLI',
    ALL:         'Universal'
  }

  const slug = slugify(input.name || 'untitled-skill')
  const date = new Date().toISOString().slice(0, 10)

  const md: string[] = []
  // Frontmatter (YAML)
  md.push('---')
  md.push(`name: ${input.name || 'Untitled Skill'}`)
  md.push(`description: ${(input.purpose || '').replace(/"/g, '\\"').slice(0, 160)}`)
  md.push(`target: ${targetMap[input.target]}`)
  md.push(`version: 0.1.0`)
  md.push(`created: ${date}`)
  md.push(`tags: [agent, skill, aindgc]`)
  md.push('---')
  md.push('')
  md.push(`# ${input.name || 'Untitled Skill'}`)
  md.push('')

  if (input.role) {
    md.push(`## Role`)
    md.push('')
    md.push(input.role)
    md.push('')
  }

  if (input.purpose) {
    md.push(`## Purpose`)
    md.push('')
    md.push(input.purpose)
    md.push('')
  }

  md.push(`## Instructions`)
  md.push('')
  md.push(input.instructions || '_Define clear, actionable instructions for the agent._')
  md.push('')

  if (input.tools.length) {
    md.push(`## Tools`)
    md.push('')
    for (const t of input.tools) md.push(`- **${t}**`)
    md.push('')
  }

  if (input.workflow) {
    md.push(`## Workflow`)
    md.push('')
    md.push(input.workflow)
    md.push('')
  }

  if (input.examples) {
    md.push(`## Examples`)
    md.push('')
    md.push(input.examples)
    md.push('')
  }

  if (input.constraints) {
    md.push(`## Constraints`)
    md.push('')
    md.push(input.constraints)
    md.push('')
  }

  md.push(`---`)
  md.push(`*Generated by Aindgc Agent Skills Generator. Compatible with ${targetMap[input.target]}.*`)

  const json = {
    schema: 'aindgc.skill/v1',
    target: input.target,
    name: input.name,
    slug,
    role: input.role,
    purpose: input.purpose,
    instructions: input.instructions,
    tools: input.tools,
    workflow: input.workflow,
    examples: input.examples,
    constraints: input.constraints,
    created_at: new Date().toISOString()
  }

  return { markdown: md.join('\n'), json }
}

function slugify(s: string): string {
  return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}
