/**
 * Agent Workflow Generator
 * Input: name, goal, triggers, steps, tools, success_criteria
 * Output: Markdown workflow definition + JSON
 */

export interface WorkflowStep {
  id: string
  name: string
  description: string
  type: 'trigger' | 'ai' | 'condition' | 'tool' | 'action' | 'output'
}

export interface WorkflowInput {
  name: string
  goal: string
  audience: string
  triggers: string[]
  steps: WorkflowStep[]
  tools: string[]
  successCriteria: string[]
  outputFormat: string
}

export interface WorkflowOutput {
  markdown: string
  json: object
}

export function generateAgentWorkflow(input: WorkflowInput): WorkflowOutput {
  const date = new Date().toISOString().slice(0, 10)

  // Markdown
  const md: string[] = []
  md.push(`# ${input.name || 'Untitled Workflow'}`)
  md.push('')
  md.push(`> Generated by Aindgc · ${date}`)
  md.push('')
  md.push(`## Goal`)
  md.push('')
  md.push(input.goal || '_Define the goal of this workflow._')
  md.push('')
  if (input.audience) {
    md.push(`**Audience**: ${input.audience}`)
    md.push('')
  }

  if (input.triggers.length) {
    md.push(`## Triggers`)
    md.push('')
    for (const t of input.triggers) md.push(`- ${t}`)
    md.push('')
  }

  if (input.steps.length) {
    md.push(`## Steps`)
    md.push('')
    input.steps.forEach((s, i) => {
      md.push(`### ${String(i + 1).padStart(2, '0')}. ${s.name || 'Step'} \`${s.type}\``)
      md.push('')
      md.push(s.description || '_Describe what this step does._')
      md.push('')
    })
  }

  if (input.tools.length) {
    md.push(`## Tools`)
    md.push('')
    for (const t of input.tools) md.push(`- ${t}`)
    md.push('')
  }

  if (input.successCriteria.length) {
    md.push(`## Success Criteria`)
    md.push('')
    for (const c of input.successCriteria) md.push(`- [ ] ${c}`)
    md.push('')
  }

  if (input.outputFormat) {
    md.push(`## Output Format`)
    md.push('')
    md.push('```json')
    md.push(input.outputFormat)
    md.push('```')
    md.push('')
  }

  md.push(`---`)
  md.push(`_This workflow was generated by Aindgc Agent Workflow Generator. Edit, version, and run it with your AI agent._`)

  // JSON
  const json = {
    schema: 'aindgc.workflow/v1',
    generated_at: new Date().toISOString(),
    name: input.name,
    goal: input.goal,
    audience: input.audience,
    triggers: input.triggers,
    steps: input.steps.map((s, i) => ({
      order: i + 1,
      id: s.id,
      name: s.name,
      type: s.type,
      description: s.description
    })),
    tools: input.tools,
    success_criteria: input.successCriteria,
    output_format: input.outputFormat ? safeParse(input.outputFormat) : null
  }

  return { markdown: md.join('\n'), json }
}

function safeParse(s: string): unknown {
  try { return JSON.parse(s) } catch { return s }
}
