/**
 * AI Coding Project Starter
 * Generates a multi-file bundle: AGENTS.md, CLAUDE.md, README.md, ARCHITECTURE.md,
 * CONTRIBUTING.md, plus the directory structure scaffold.
 */

export type Stack =
  | 'Vue 3' | 'React' | 'Next.js' | 'Nuxt 3'
  | 'Spring Boot' | 'FastAPI' | 'Node.js (Express)' | 'Node.js (NestJS)'
  | 'Go (Gin)' | 'Python (Django)'

export type AiTarget = 'CLAUDE_CODE' | 'CODEX' | 'CURSOR' | 'GEMINI_CLI'

export interface CodingInput {
  projectName: string
  description: string
  frontend: Stack | ''
  backend: Stack | ''
  fullStack: boolean
  aiTarget: AiTarget
  features: string[]
  conventions: string
}

export interface CodingOutput {
  files: { name: string; content: string }[]
}

const targetFileMap: Record<AiTarget, string> = {
  CLAUDE_CODE: 'CLAUDE.md',
  CODEX:       'AGENTS.md',
  CURSOR:      '.cursorrules',
  GEMINI_CLI:  'GEMINI.md'
}

export function generateCodingProject(input: CodingInput): CodingOutput {
  const slug = slugify(input.projectName || 'my-project')
  const date = new Date().toISOString().slice(0, 10)
  const aiFileName = targetFileMap[input.aiTarget]
  const targetLabels: Record<AiTarget, string> = {
    CLAUDE_CODE: 'Claude Code',
    CODEX:       'Codex CLI',
    CURSOR:      'Cursor',
    GEMINI_CLI:  'Gemini CLI'
  }

  const stack: string[] = []
  if (input.frontend) stack.push(input.frontend)
  if (input.backend) stack.push(input.backend)
  const stackLine = stack.length ? stack.join(' + ') : 'TBD'

  const files: { name: string; content: string }[] = []

  // ===== README.md =====
  let readme = `# ${input.projectName || 'My Project'}\n\n`
  readme += `> ${input.description || '_Short description of the project._'}\n\n`
  readme += `**Stack**: ${stackLine}\n\n`
  readme += `**AI Coding target**: ${targetLabels[input.aiTarget]}\n\n`
  readme += `**Created**: ${date} · generated by Aindgc\n\n`
  readme += `## Quick start\n\n`
  if (input.frontend === 'Vue 3' || input.frontend === 'Nuxt 3') {
    readme += `\`\`\`bash\ncd frontend && pnpm install && pnpm dev\n\`\`\`\n\n`
  } else if (input.frontend) {
    readme += `\`\`\`bash\ncd frontend && pnpm install && pnpm dev\n\`\`\`\n\n`
  }
  if (input.backend) {
    readme += `\`\`\`bash\ncd backend && ./mvnw spring-boot:run   # or: pnpm dev / uvicorn main:app\n\`\`\`\n\n`
  }
  readme += `## Features\n\n`
  for (const f of input.features) readme += `- ${f}\n`
  if (!input.features.length) readme += `_Add features here._\n`
  readme += `\n## Project layout\n\nSee ARCHITECTURE.md.\n\n## Contributing\n\nSee CONTRIBUTING.md.\n`
  files.push({ name: 'README.md', content: readme })

  // ===== ARCHITECTURE.md =====
  let arch = `# Architecture\n\n`
  arch += `> How the pieces fit together.\n\n`
  arch += `## High level\n\n`
  arch += `\`\`\`\n`
  if (input.frontend && input.backend) {
    arch += `[Browser]\n   ↓\n[Frontend — ${input.frontend}]\n   ↓ HTTP/JSON\n[Backend — ${input.backend}]\n   ↓\n[Database]\n`
  } else if (input.frontend) {
    arch += `[Browser]\n   ↓\n[Frontend — ${input.frontend}]\n`
  } else if (input.backend) {
    arch += `[Client]\n   ↓\n[Backend — ${input.backend}]\n   ↓\n[Database]\n`
  } else {
    arch += `_Define the architecture._\n`
  }
  arch += `\`\`\`\n\n`
  arch += `## Directory layout\n\n`
  arch += '```\n'
  arch += `${slug}/\n`
  if (input.frontend) {
    arch += `├── frontend/        # ${input.frontend}\n`
    arch += `│   ├── src/\n`
    arch += `│   ├── public/\n`
    arch += `│   ├── package.json\n`
    arch += `│   └── README.md\n`
  }
  if (input.backend) {
    arch += `├── backend/         # ${input.backend}\n`
    arch += `│   ├── src/\n`
    arch += `│   ├── pom.xml / package.json / pyproject.toml\n`
    arch += `│   └── README.md\n`
  }
  arch += `├── docs/\n`
  arch += `├── tests/\n`
  arch += `├── ${aiFileName}        # AI agent instructions\n`
  arch += `├── README.md\n`
  arch += `└── ARCHITECTURE.md\n`
  arch += '```\n\n'
  arch += `## Conventions\n\n${input.conventions || '_Document conventions as they emerge._'}\n`
  files.push({ name: 'ARCHITECTURE.md', content: arch })

  // ===== AI agent instructions =====
  let aiDoc = `# AI Agent Instructions\n\n`
  aiDoc += `> Read this before making changes. Generated for ${targetLabels[input.aiTarget]}.\n\n`
  aiDoc += `## Project\n\n**${input.projectName || 'My Project'}** — ${input.description || '_Description_'}\n\n`
  aiDoc += `**Stack**: ${stackLine}\n\n`
  aiDoc += `## Working principles\n\n`
  aiDoc += `1. **Read before write.** Always read the relevant files first.\n`
  aiDoc += `2. **Stay consistent.** Match existing code style, naming, and patterns.\n`
  aiDoc += `3. **Small steps.** Make focused, reviewable changes.\n`
  aiDoc += `4. **Verify.** Run tests / type-check / build after changes.\n`
  aiDoc += `5. **No scope creep.** If a task implies larger changes, ask first.\n\n`
  aiDoc += `## Directory boundaries\n\n`
  aiDoc += `- ${input.frontend ? `\`frontend/\` — ${input.frontend} code only. Don't add backend code here.\n` : ''}`
  aiDoc += `- ${input.backend ? `\`backend/\` — ${input.backend} code only.\n` : ''}`
  aiDoc += `- \`docs/\` — design notes, decisions, RFCs.\n`
  aiDoc += `- \`tests/\` — end-to-end / integration tests.\n\n`
  aiDoc += `## Conventions\n\n${input.conventions || '_Add team conventions._'}\n\n`
  aiDoc += `## Features (current scope)\n\n`
  for (const f of input.features) aiDoc += `- ${f}\n`
  if (!input.features.length) aiDoc += `_List the features currently in scope._\n`
  aiDoc += `\n## Done when\n\n- [ ] Code matches existing style\n- [ ] No new lint / type errors\n- [ ] Tests pass (or new tests added for new behavior)\n- [ ] CHANGELOG / commit message describes the change\n`
  files.push({ name: aiFileName, content: aiDoc })

  // ===== CONTRIBUTING.md =====
  let contrib = `# Contributing\n\n`
  contrib += `## Workflow\n\n`
  contrib += `1. Branch from \`main\`.\n`
  contrib += `2. Make focused commits.\n`
  contrib += `3. Open a PR with a clear description.\n\n`
  contrib += `## Commit style\n\n`
  contrib += `Use Conventional Commits: \`feat:\`, \`fix:\`, \`docs:\`, \`refactor:\`, \`test:\`, \`chore:\`.\n\n`
  contrib += `## Code style\n\n`
  contrib += `- Match the existing patterns in each directory.\n`
  contrib += `- Keep changes minimal — don't refactor unrelated code.\n`
  contrib += `- Prefer explicit over clever.\n\n`
  contrib += `## Reporting issues\n\n`
  contrib += `Include: expected vs actual, reproduction steps, environment.\n`
  files.push({ name: 'CONTRIBUTING.md', content: contrib })

  // ===== CHANGELOG.md =====
  let chlog = `# Changelog\n\n`
  chlog += `## [Unreleased]\n\n`
  chlog += `### Added\n`
  chlog += `- Initial project scaffold generated by Aindgc.\n\n`
  chlog += `### Notes\n`
  chlog += `- Stack: ${stackLine}\n`
  chlog += `- AI target: ${targetLabels[input.aiTarget]}\n`
  files.push({ name: 'CHANGELOG.md', content: chlog })

  return { files }
}

function slugify(s: string): string {
  return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}
