/**
 * AI Context Builder
 * Produces a CONTEXT.md file — a structured context package for AI agents.
 */

export interface ContextInput {
  purpose: string
  audience: string
  scope: string
  keyInfo: string
  constraints: string
  examples: string
  successSignals: string
}

export function generateContext(input: ContextInput): { markdown: string; json: object } {
  const date = new Date().toISOString().slice(0, 10)
  const md: string[] = []

  md.push(`# Context`)
  md.push('')
  md.push(`> Generated by Aindgc · ${date}`)
  md.push('')

  if (input.purpose) {
    md.push(`## 1. Purpose`)
    md.push('')
    md.push(input.purpose)
    md.push('')
  }

  if (input.audience) {
    md.push(`## 2. Audience`)
    md.push('')
    md.push(input.audience)
    md.push('')
  }

  if (input.scope) {
    md.push(`## 3. Scope`)
    md.push('')
    md.push(`**In scope:**`)
    md.push('')
    md.push(input.scope)
    md.push('')
  }

  if (input.keyInfo) {
    md.push(`## 4. Key Information`)
    md.push('')
    md.push(input.keyInfo)
    md.push('')
  }

  if (input.constraints) {
    md.push(`## 5. Constraints`)
    md.push('')
    md.push(input.constraints)
    md.push('')
  }

  if (input.examples) {
    md.push(`## 6. Examples`)
    md.push('')
    md.push(input.examples)
    md.push('')
  }

  if (input.successSignals) {
    md.push(`## 7. Success Signals`)
    md.push('')
    md.push(input.successSignals)
    md.push('')
  }

  md.push(`---`)
  md.push(`*This context package is designed to be pasted into any AI agent's system prompt or context window.*`)

  const json = {
    schema: 'aindgc.context/v1',
    generated_at: new Date().toISOString(),
    purpose: input.purpose,
    audience: input.audience,
    scope: input.scope,
    key_information: input.keyInfo,
    constraints: input.constraints,
    examples: input.examples,
    success_signals: input.successSignals
  }

  return { markdown: md.join('\n'), json }
}
