/**
 * Output Schema Generator
 * Produces: JSON Schema, TypeScript types, Markdown doc.
 */

export type FieldType = 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object' | 'null'

export interface SchemaField {
  name: string
  type: FieldType
  description?: string
  required?: boolean
  enum?: string[]
  format?: string  // date-time, email, uri, etc.
  defaultValue?: string
  itemType?: FieldType  // for arrays
}

export interface SchemaInput {
  name: string
  description: string
  fields: SchemaField[]
}

export interface SchemaOutput {
  markdown: string
  jsonSchema: object
  typescript: string
}

export function generateOutputSchema(input: SchemaInput): SchemaOutput {
  const slug = slugify(input.name || 'output')

  // JSON Schema
  const properties: Record<string, unknown> = {}
  const required: string[] = []
  for (const f of input.fields) {
    properties[f.name] = buildJsonProperty(f)
    if (f.required) required.push(f.name)
  }

  const jsonSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: `https://aindgc.com/schemas/${slug}.json`,
    title: input.name || 'Output',
    description: input.description || '',
    type: 'object',
    properties,
    required: required.length ? required : undefined,
    additionalProperties: false
  }

  // TypeScript
  const tsLines: string[] = []
  tsLines.push(`/**`)
  tsLines.push(` * ${input.name || 'Output'}`)
  if (input.description) tsLines.push(` * ${input.description}`)
  tsLines.push(` */`)
  tsLines.push(`export interface ${toPascal(input.name || 'Output')} {`)
  for (const f of input.fields) {
    if (f.description) {
      tsLines.push(`  /**`)
      tsLines.push(`   * ${f.description.replace(/\n/g, ' ')}`)
      tsLines.push(`   */`)
    }
    const opt = f.required ? '' : '?'
    let type = 'unknown'
    switch (f.type) {
      case 'string': type = 'string'; break
      case 'number':
      case 'integer': type = 'number'; break
      case 'boolean': type = 'boolean'; break
      case 'null':    type = 'null'; break
      case 'array':   type = `${f.itemType ? tsType(f.itemType) : 'unknown'}[]`; break
      case 'object':  type = 'Record<string, unknown>'; break
    }
    if (f.enum?.length) type = f.enum.map(e => `'${e}'`).join(' | ')
    tsLines.push(`  ${f.name}${opt}: ${type};`)
  }
  tsLines.push(`}`)
  const typescript = tsLines.join('\n')

  // Markdown doc
  const md: string[] = []
  md.push(`# ${input.name || 'Output Schema'}`)
  md.push('')
  if (input.description) {
    md.push(input.description)
    md.push('')
  }
  md.push(`## Fields`)
  md.push('')
  md.push(`| Name | Type | Required | Description |`)
  md.push(`|------|------|----------|-------------|`)
  for (const f of input.fields) {
    let typeStr = f.type.toLowerCase()
    if (f.type === 'array' && f.itemType) typeStr = `${f.itemType.toLowerCase()}[]`
    if (f.enum?.length) typeStr = `enum(${f.enum.join(', ')})`
    md.push(`| \`${f.name}\` | ${typeStr} | ${f.required ? 'yes' : 'no'} | ${(f.description || '').replace(/\|/g, '\\|')} |`)
  }
  md.push('')
  md.push(`## JSON Schema`)
  md.push('')
  md.push('```json')
  md.push(JSON.stringify(jsonSchema, null, 2))
  md.push('```')
  md.push('')
  md.push(`## TypeScript`)
  md.push('')
  md.push('```ts')
  md.push(typescript)
  md.push('```')
  md.push('')
  md.push(`*Generated by Aindgc Output Schema Generator.*`)

  return { markdown: md.join('\n'), jsonSchema, typescript }
}

function buildJsonProperty(f: SchemaField): Record<string, unknown> {
  const base: Record<string, unknown> = {}
  if (f.description) base.description = f.description
  if (f.enum?.length) {
    base.type = 'string'
    base.enum = f.enum
  } else if (f.type === 'array') {
    base.type = 'array'
    base.items = f.itemType ? { type: f.itemType } : { type: 'string' }
  } else {
    base.type = f.type
  }
  if (f.format) base.format = f.format
  if (f.defaultValue !== undefined && f.defaultValue !== '') base.default = coerce(f.defaultValue, f.type)
  return base
}

function coerce(v: string, type: FieldType): unknown {
  if (type === 'number' || type === 'integer') return Number(v)
  if (type === 'boolean') return v === 'true'
  return v
}

function tsType(t: FieldType): string {
  switch (t) {
    case 'string':  return 'string'
    case 'number':
    case 'integer': return 'number'
    case 'boolean': return 'boolean'
    case 'null':    return 'null'
    default:        return 'unknown'
  }
}

function toPascal(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function slugify(s: string): string {
  return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}
