/**
 * Prompt Structure Builder
 * Generates a structured prompt for one-shot tasks.
 */

export interface PromptInput {
  task: string
  role: string
  audience: string
  context: string
  constraints: string
  outputFormat: string
  examples: string
  tone: 'formal' | 'casual' | 'technical' | 'friendly'
  includeSteps: boolean
}

export function generatePrompt(input: PromptInput): { markdown: string; json: object } {
  const toneMap: Record<PromptInput['tone'], string> = {
    formal:    'Use a formal, professional tone. Avoid colloquialisms.',
    casual:    'Use a casual, approachable tone.',
    technical: 'Use precise technical language. Assume the reader is an expert.',
    friendly:  'Use a warm, friendly tone. Encourage the reader.'
  }

  const md: string[] = []
  md.push(`# Prompt`)
  md.push('')

  if (input.role) {
    md.push(`## Role`)
    md.push('')
    md.push(`You are ${input.role}.`)
    md.push('')
  }

  if (input.audience) {
    md.push(`## Audience`)
    md.push('')
    md.push(`Your audience: ${input.audience}.`)
    md.push('')
  }

  md.push(`## Task`)
  md.push('')
  md.push(input.task || '_Describe the task you want done._')
  md.push('')

  if (input.context) {
    md.push(`## Context`)
    md.push('')
    md.push(input.context)
    md.push('')
  }

  if (input.includeSteps) {
    md.push(`## Approach`)
    md.push('')
    md.push(`Think through this step by step:\n`)
    md.push(`1. Understand the request and identify unknowns.`)
    md.push(`2. Lay out the structure of your answer.`)
    md.push(`3. Fill in each section.`)
    md.push(`4. Self-review against constraints before responding.`)
    md.push('')
  }

  if (input.constraints) {
    md.push(`## Constraints`)
    md.push('')
    md.push(input.constraints)
    md.push('')
  }

  md.push(`## Tone`)
  md.push('')
  md.push(toneMap[input.tone])
  md.push('')

  if (input.outputFormat) {
    md.push(`## Output format`)
    md.push('')
    md.push(input.outputFormat)
    md.push('')
  }

  if (input.examples) {
    md.push(`## Examples`)
    md.push('')
    md.push(input.examples)
    md.push('')
  }

  md.push(`---`)
  md.push(`*Generated by Aindgc Prompt Structure Builder.*`)

  const json = {
    schema: 'aindgc.prompt/v1',
    role: input.role,
    audience: input.audience,
    task: input.task,
    context: input.context,
    constraints: input.constraints,
    output_format: input.outputFormat,
    examples: input.examples,
    tone: input.tone,
    include_steps: input.includeSteps
  }

  return { markdown: md.join('\n'), json }
}
