-- =====================================================================
-- Aindgc · Schema (H2)
--
-- AUTO-GENERATED from 01-schema.sql (MySQL 8) by deploy/docker/tools/mysql2h2.mjs
-- Do not hand-edit: regenerate instead, or the two schemas will drift.
--
-- Differences vs the MySQL original, all intentional:
--   * inline KEY / UNIQUE KEY hoisted into standalone CREATE INDEX
--   * index names prefixed with the table name (H2 index names are schema-global,
--     MySQL's are per-table, and this schema reused uk_share / idx_user everywhere)
--   * BIGINT UNSIGNED AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--   * JSON -> CLOB (mapped to String by the app; avoids H2 JSON parse strictness)
--   * MEDIUMTEXT / TEXT -> CLOB (H2 2.x has neither type)
--   * ON UPDATE CURRENT_TIMESTAMP dropped — MybatisPlusMetaObjectHandler stamps
--     updated_at on every update, so the behaviour is preserved
--   * inline column COMMENT dropped (H2 uses COMMENT ON COLUMN)
-- =====================================================================

-- ---------------------------------------------------------------------
-- User & Auth
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(64)  NOT NULL,
    email           VARCHAR(128) NOT NULL,
    password_hash   VARCHAR(128) NOT NULL,
    nickname        VARCHAR(64)  NULL,
    avatar          VARCHAR(255) NULL,
    bio             VARCHAR(500) NULL,
    status          TINYINT      NOT NULL DEFAULT 1,
    last_login_at   DATETIME     NULL,
    last_login_ip   VARCHAR(64)  NULL,
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_user_uk_username ON t_user (username);
CREATE UNIQUE INDEX IF NOT EXISTS t_user_uk_email ON t_user (email);
CREATE INDEX IF NOT EXISTS t_user_idx_status ON t_user (status, deleted);

CREATE TABLE IF NOT EXISTS t_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR_IGNORECASE(32) NOT NULL,
    name            VARCHAR(64) NOT NULL,
    description     VARCHAR(255) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_role_uk_code ON t_role (code);

CREATE TABLE IF NOT EXISTS t_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR_IGNORECASE(64) NOT NULL,
    name            VARCHAR(64) NOT NULL,
    type            VARCHAR(16) NOT NULL DEFAULT 'API',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_permission_uk_code ON t_permission (code);

CREATE TABLE IF NOT EXISTS t_user_role (
    user_id         BIGINT NOT NULL,
    role_id         BIGINT NOT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS t_user_role_idx_role ON t_user_role (role_id);

CREATE TABLE IF NOT EXISTS t_role_permission (
    role_id         BIGINT NOT NULL,
    permission_id   BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX IF NOT EXISTS t_role_permission_idx_perm ON t_role_permission (permission_id);

-- ---------------------------------------------------------------------
-- Tools
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_tool_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(64) NOT NULL,
    slug            VARCHAR_IGNORECASE(64) NOT NULL,
    description     VARCHAR(255) NULL,
    sort            INT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_tool_category_uk_slug ON t_tool_category (slug);

CREATE TABLE IF NOT EXISTS t_tool (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug            VARCHAR_IGNORECASE(64) NOT NULL,
    name            VARCHAR(64) NOT NULL,
    tagline         VARCHAR(255) NULL,
    description     CLOB NULL,
    icon            VARCHAR(64) NULL,
    category_id     BIGINT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    config_json     CLOB NULL,
    output_format   VARCHAR(16) NOT NULL DEFAULT 'MARKDOWN',
    featured        TINYINT NOT NULL DEFAULT 0,
    sort            INT NOT NULL DEFAULT 0,
    view_count      BIGINT NOT NULL DEFAULT 0,
    generate_count  BIGINT NOT NULL DEFAULT 0,
    seo_title       VARCHAR(128) NULL,
    seo_description VARCHAR(255) NULL,
    seo_keywords    VARCHAR(255) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_tool_uk_slug ON t_tool (slug);
CREATE INDEX IF NOT EXISTS t_tool_idx_status_featured ON t_tool (status, featured, deleted);
CREATE INDEX IF NOT EXISTS t_tool_idx_category ON t_tool (category_id, deleted);

CREATE TABLE IF NOT EXISTS t_tool_usage (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tool_id         BIGINT NOT NULL,
    user_id         BIGINT NULL,
    anonymous_id    VARCHAR(64) NULL,
    action          VARCHAR(16) NOT NULL,
    ip              VARCHAR(64) NULL,
    user_agent      VARCHAR(500) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS t_tool_usage_idx_tool_action ON t_tool_usage (tool_id, action, created_at);
CREATE INDEX IF NOT EXISTS t_tool_usage_idx_user ON t_tool_usage (user_id, created_at);

-- ---------------------------------------------------------------------
-- Workflow
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_workflow_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(64) NOT NULL,
    slug            VARCHAR_IGNORECASE(64) NOT NULL,
    sort            INT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_workflow_category_uk_slug ON t_workflow_category (slug);

CREATE TABLE IF NOT EXISTS t_workflow_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug            VARCHAR_IGNORECASE(96) NOT NULL,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(500) NULL,
    cover           VARCHAR(255) NULL,
    category_id     BIGINT NULL,
    complexity      VARCHAR(16) NOT NULL DEFAULT 'BEGINNER',
    nodes_json      CLOB NULL,
    edges_json      CLOB NULL,
    config_json     CLOB NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    view_count      BIGINT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_workflow_template_uk_slug ON t_workflow_template (slug);
CREATE INDEX IF NOT EXISTS t_workflow_template_idx_status ON t_workflow_template (status, deleted, complexity);

CREATE TABLE IF NOT EXISTS t_workflow (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NOT NULL,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(500) NULL,
    nodes_json      CLOB NULL,
    edges_json      CLOB NULL,
    is_template     TINYINT NOT NULL DEFAULT 0,
    visibility      VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS t_workflow_idx_user ON t_workflow (user_id, deleted, created_at);

-- ---------------------------------------------------------------------
-- Skills
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_skill_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug            VARCHAR_IGNORECASE(96) NOT NULL,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(500) NULL,
    content_md      CLOB NOT NULL,
    target          VARCHAR(32) NOT NULL DEFAULT 'ALL',
    category_id     BIGINT NULL,
    view_count      BIGINT NOT NULL DEFAULT 0,
    generate_count  BIGINT NOT NULL DEFAULT 0,
    status          VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_skill_template_uk_slug ON t_skill_template (slug);
CREATE INDEX IF NOT EXISTS t_skill_template_idx_target_status ON t_skill_template (target, status, deleted);

CREATE TABLE IF NOT EXISTS t_skill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NULL,
    name            VARCHAR(128) NOT NULL,
    role            VARCHAR(255) NULL,
    purpose         VARCHAR(500) NULL,
    content_md      CLOB NOT NULL,
    target          VARCHAR(32) NOT NULL DEFAULT 'CLAUDE_CODE',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS t_skill_idx_user ON t_skill (user_id, deleted, created_at);

-- ---------------------------------------------------------------------
-- AI Coding
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_coding_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug            VARCHAR_IGNORECASE(96) NOT NULL,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(500) NULL,
    frontend_stack  VARCHAR(64) NULL,
    backend_stack   VARCHAR(64) NULL,
    ai_target       VARCHAR(32) NOT NULL DEFAULT 'CLAUDE_CODE',
    structure_json  CLOB NULL,
    files_json      CLOB NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_coding_template_uk_slug ON t_coding_template (slug);
CREATE INDEX IF NOT EXISTS t_coding_template_idx_status ON t_coding_template (status, deleted);

-- ---------------------------------------------------------------------
-- Articles (Insights)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_article_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(64) NOT NULL,
    slug            VARCHAR_IGNORECASE(64) NOT NULL,
    description     VARCHAR(255) NULL,
    sort            INT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_article_category_uk_slug ON t_article_category (slug);

CREATE TABLE IF NOT EXISTS t_article_tag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(64) NOT NULL,
    slug            VARCHAR_IGNORECASE(64) NOT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_article_tag_uk_slug ON t_article_tag (slug);

CREATE TABLE IF NOT EXISTS t_article (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255) NOT NULL,
    slug            VARCHAR_IGNORECASE(128) NOT NULL,
    cover           VARCHAR(255) NULL,
    summary         VARCHAR(500) NULL,
    content_md      CLOB NOT NULL,
    category_id     BIGINT NULL,
    author_id       BIGINT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    is_featured     TINYINT NOT NULL DEFAULT 0,
    view_count      BIGINT NOT NULL DEFAULT 0,
    like_count      BIGINT NOT NULL DEFAULT 0,
    seo_title       VARCHAR(128) NULL,
    seo_description VARCHAR(255) NULL,
    seo_keywords    VARCHAR(255) NULL,
    canonical_url   VARCHAR(255) NULL,
    og_image        VARCHAR(255) NULL,
    published_at    DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_article_uk_slug ON t_article (slug);
CREATE INDEX IF NOT EXISTS t_article_idx_status ON t_article (status, is_featured, published_at, deleted);
CREATE INDEX IF NOT EXISTS t_article_idx_category ON t_article (category_id, deleted);
CREATE INDEX IF NOT EXISTS t_article_idx_author ON t_article (author_id);

CREATE TABLE IF NOT EXISTS t_article_tag_relation (
    article_id      BIGINT NOT NULL,
    tag_id          BIGINT NOT NULL,
    PRIMARY KEY (article_id, tag_id)
);
CREATE INDEX IF NOT EXISTS t_article_tag_relation_idx_tag ON t_article_tag_relation (tag_id);

-- ---------------------------------------------------------------------
-- Cases
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_case_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(64) NOT NULL,
    slug            VARCHAR_IGNORECASE(64) NOT NULL,
    description     VARCHAR(255) NULL,
    sort            INT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_case_category_uk_slug ON t_case_category (slug);

CREATE TABLE IF NOT EXISTS t_case_project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255) NOT NULL,
    slug            VARCHAR_IGNORECASE(128) NOT NULL,
    cover           VARCHAR(255) NULL,
    summary         VARCHAR(500) NULL,
    problem_md      CLOB NULL,
    thinking_md     CLOB NULL,
    approach_md     CLOB NULL,
    architecture_md CLOB NULL,
    implementation_md CLOB NULL,
    result_md       CLOB NULL,
    learned_md      CLOB NULL,
    technologies_json CLOB NULL,
    ai_models_json    CLOB NULL,
    type            VARCHAR(16) NOT NULL DEFAULT 'EXPERIMENT',
    status          VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    is_featured     TINYINT NOT NULL DEFAULT 0,
    view_count      BIGINT NOT NULL DEFAULT 0,
    repo_url        VARCHAR(255) NULL,
    demo_url        VARCHAR(255) NULL,
    category_id     BIGINT NULL,
    published_at    DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_case_project_uk_slug ON t_case_project (slug);
CREATE INDEX IF NOT EXISTS t_case_project_idx_type_status ON t_case_project (type, status, is_featured, deleted);
CREATE INDEX IF NOT EXISTS t_case_project_idx_category ON t_case_project (category_id);

-- ---------------------------------------------------------------------
-- ROI & Checkup
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_roi_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NULL,
    anonymous_id    VARCHAR(64) NULL,
    inputs_json     CLOB NOT NULL,
    outputs_json    CLOB NOT NULL,
    share_token     VARCHAR(64) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_roi_record_uk_share ON t_roi_record (share_token);
CREATE INDEX IF NOT EXISTS t_roi_record_idx_user ON t_roi_record (user_id, created_at);
CREATE INDEX IF NOT EXISTS t_roi_record_idx_anonymous ON t_roi_record (anonymous_id, created_at);

CREATE TABLE IF NOT EXISTS t_checkup_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NULL,
    anonymous_id    VARCHAR(64) NULL,
    answers_json    CLOB NOT NULL,
    score           INT NOT NULL,
    opportunities_json CLOB NULL,
    share_token     VARCHAR(64) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_checkup_record_uk_share ON t_checkup_record (share_token);
CREATE INDEX IF NOT EXISTS t_checkup_record_idx_user ON t_checkup_record (user_id, created_at);
CREATE INDEX IF NOT EXISTS t_checkup_record_idx_score ON t_checkup_record (score);

-- ---------------------------------------------------------------------
-- SEO
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_seo_page (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    page_key        VARCHAR_IGNORECASE(64) NOT NULL,
    page_path       VARCHAR(255) NOT NULL,
    title           VARCHAR(128) NULL,
    description     VARCHAR(255) NULL,
    keywords        VARCHAR(255) NULL,
    canonical       VARCHAR(255) NULL,
    og_image        VARCHAR(255) NULL,
    robots          VARCHAR(64) NULL,
    schema_type     VARCHAR(64) NULL,
    custom_jsonld   CLOB NULL,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_seo_page_uk_page_key ON t_seo_page (page_key);
CREATE INDEX IF NOT EXISTS t_seo_page_idx_path ON t_seo_page (page_path);

CREATE TABLE IF NOT EXISTS t_keyword (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    term            VARCHAR(128) NOT NULL,
    locale          VARCHAR(8) NOT NULL DEFAULT 'en',
    search_volume   INT NULL,
    difficulty      INT NULL,
    target_url      VARCHAR(255) NULL,
    priority        INT NOT NULL DEFAULT 0,
    notes           VARCHAR(500) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_keyword_uk_term_locale ON t_keyword (term, locale);
CREATE INDEX IF NOT EXISTS t_keyword_idx_priority ON t_keyword (priority);

-- ---------------------------------------------------------------------
-- System
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS t_site_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    config_key      VARCHAR_IGNORECASE(64) NOT NULL,
    config_value    CLOB NOT NULL,
    value_type      VARCHAR(16) NOT NULL DEFAULT 'STRING',
    description     VARCHAR(255) NULL,
    is_public       TINYINT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_site_config_uk_config_key ON t_site_config (config_key);

CREATE TABLE IF NOT EXISTS t_ad_slot (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR_IGNORECASE(64) NOT NULL,
    description     VARCHAR(255) NULL,
    enabled         TINYINT NOT NULL DEFAULT 0,
    content_html    CLOB NULL,
    sort            INT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS t_ad_slot_uk_code ON t_ad_slot (code);
CREATE INDEX IF NOT EXISTS t_ad_slot_idx_enabled ON t_ad_slot (enabled, deleted, sort);

CREATE TABLE IF NOT EXISTS t_operation_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NULL,
    module          VARCHAR(64) NULL,
    action          VARCHAR(64) NULL,
    request_data    CLOB NULL,
    response_data   CLOB NULL,
    ip              VARCHAR(64) NULL,
    ua              VARCHAR(500) NULL,
    status          TINYINT NULL,
    duration_ms     BIGINT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS t_operation_log_idx_user_time ON t_operation_log (user_id, created_at);
CREATE INDEX IF NOT EXISTS t_operation_log_idx_module_action ON t_operation_log (module, action, created_at);

CREATE TABLE IF NOT EXISTS t_visitor_stat (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    anonymous_id    VARCHAR(64) NULL,
    user_id         BIGINT NULL,
    page            VARCHAR(255) NOT NULL,
    action_type     VARCHAR(32) NULL,
    target_id       BIGINT NULL,
    target_type     VARCHAR(32) NULL,
    referer         VARCHAR(500) NULL,
    ip              VARCHAR(64) NULL,
    user_agent      VARCHAR(500) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS t_visitor_stat_idx_page_time ON t_visitor_stat (page, created_at);
CREATE INDEX IF NOT EXISTS t_visitor_stat_idx_anon ON t_visitor_stat (anonymous_id, created_at);
CREATE INDEX IF NOT EXISTS t_visitor_stat_idx_target ON t_visitor_stat (target_type, target_id, created_at);

