// Aindgc shared types
// This file is a placeholder so the types directory is tracked by git.
// Add cross-module type declarations here. Component & auto-import types
// are auto-generated by unplugin-* (see vite.config.ts) and gitignored.

export type Brand<K, T> = K & { readonly __brand: T }

export type Nullable<T> = T | null

export type AsyncResult<T> = Promise<T>

export interface PageParams {
  page?: number
  size?: number
  keyword?: string
  orderBy?: string
  order?: 'asc' | 'desc'
}

export interface ApiPage<T> {
  list: T[]
  total: number
  page: number
  size: number
}
