#!/usr/bin/env bash
# =====================================================================
# Aindgc · One-shot deployer
# Runs on the SERVER (after server-init.sh)
# Builds frontend, uploads backend jar, runs DB migration, restarts.
# Usage: sudo bash deploy.sh
# =====================================================================
set -euo pipefail

AINDGC_ROOT="${AINDGC_ROOT:-/opt/aindgc}"
AINDGC_USER="${AINDGC_USER:-aindgc}"
DOMAIN="${DOMAIN:-aindgc.com}"
ADMIN_DOMAIN="${ADMIN_DOMAIN:-admin.aindgc.com}"
API_DOMAIN="${API_DOMAIN:-api.aindgc.com}"
NGINX_SITE="/etc/nginx/sites-available/aindgc"
ENV_FILE="/etc/aindgc/backend.env"

log() { printf "\033[1;34m[deploy]\033[0m %s\n" "$*"; }
ok()  { printf "\033[1;32m[ ok]\033[0m %s\n" "$*"; }
err() { printf "\033[1;31m[err]\033[0m %s\n" "$*" >&2; }

# ---- Preflight ----
if [[ $EUID -ne 0 ]]; then err "Must run as root"; exit 1; fi
if [[ ! -d "$AINDGC_ROOT" ]]; then err "$AINDGC_ROOT not found"; exit 1; fi
if [[ ! -f "$ENV_FILE" ]]; then err "$ENV_FILE not found — copy from deploy/backend.env.example"; exit 1; fi

cd "$AINDGC_ROOT"

# ---- 1. Build frontend ----
log "Building frontend..."
if [[ ! -d frontend ]]; then err "frontend/ not found in $AINDGC_ROOT"; exit 1; fi
cd frontend
sudo -u "$AINDGC_USER" bash -c "pnpm install --frozen-lockfile && pnpm build"
cd ..
ok "Frontend built → frontend/dist/"

# ---- 2. Deploy frontend ----
log "Deploying frontend to /var/www/aindgc/..."
DEST="/var/www/aindgc"
mkdir -p "$DEST"
rsync -a --delete --exclude='.git' frontend/dist/ "$DEST/"
chown -R "$AINDGC_USER:$AINDGC_USER" "$DEST"
ok "Frontend → $DEST"

# ---- 3. Backend: upload jar (assumed already copied via scp) ----
BACKEND_JAR="$AINDGC_ROOT/backend/aindgc-backend.jar"
if [[ ! -f "$BACKEND_JAR" ]]; then
  log "Backend jar not found — attempting to build locally..."
  if [[ -d backend ]]; then
    sudo -u "$AINDGC_USER" bash -c "cd backend && mvn clean package -DskipTests"
    [[ -f "$BACKEND_JAR" ]] || { err "Backend build failed"; exit 1; }
  else
    err "backend/ not found and no jar in $AINDGC_ROOT/backend/"
    exit 1
  fi
fi
chown "$AINDGC_USER:$AINDGC_USER" "$BACKEND_JAR"
ok "Backend jar ready"

# ---- 4. Install / upgrade systemd unit ----
log "Installing systemd unit..."
cp deploy/aindgc-backend.service /etc/systemd/system/aindgc-backend.service
systemctl daemon-reload
systemctl enable aindgc-backend.service
systemctl restart aindgc-backend.service
ok "Backend service restarted"

# ---- 5. Wait for backend to be healthy ----
log "Waiting for /api/health..."
for i in $(seq 1 30); do
  if curl -fs http://127.0.0.1:8080/api/health >/dev/null 2>&1; then
    ok "Backend healthy (attempt $i)"
    break
  fi
  sleep 2
done

# ---- 6. Initialise DB schema + content (idempotent) ----
log "Running SQL migrations..."
sudo -u "$AINDGC_USER" mysql --user=aindgc --password="$(grep DB_PASS $ENV_FILE | cut -d= -f2)" aindgc < backend/src/main/resources/sql/01-schema.sql
ok "Schema applied (ContentDataInitializer will seed content on first boot)"

# ---- 7. Install / refresh Nginx config ----
log "Writing Nginx site config..."
cat > "$NGINX_SITE" <<NGINX
# Auto-generated by deploy.sh — DO NOT EDIT
# Edit deploy/nginx.prod.conf.template instead.

# HTTP → HTTPS
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN} ${ADMIN_DOMAIN} ${API_DOMAIN};
    return 301 https://\$host\$request_uri;
}

# Main site
server {
    listen 443 ssl http2;
    server_name ${DOMAIN} www.${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options    "nosniff" always;
    add_header X-Frame-Options           "SAMEORIGIN" always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;

    root /var/www/aindgc;
    index index.html;

    # Static assets — long cache
    location ~* \.(?:js|css|woff2?|ttf|otf|svg|png|jpe?g|gif|webp|ico)\$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Sitemap / robots → backend
    location = /sitemap.xml { proxy_pass http://127.0.0.1:8080; }
    location = /robots.txt  { proxy_pass http://127.0.0.1:8080; }

    # Backend API
    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }

    # SPA fallback
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    gzip on;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    access_log /var/log/nginx/aindgc.access.log;
    error_log  /var/log/nginx/aindgc.error.log;
}

# Admin subdomain
server {
    listen 443 ssl http2;
    server_name ${ADMIN_DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/aindgc;
    index index.html;

    location / { try_files \$uri \$uri/ /index.html; }
    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    access_log /var/log/nginx/aindgc-admin.access.log;
    error_log  /var/log/nginx/aindgc-admin.error.log;
}
NGINX

ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/aindgc
nginx -t
systemctl reload nginx
ok "Nginx reloaded"

# ---- 8. HTTPS via Let's Encrypt (first run only) ----
if [[ ! -d /etc/letsencrypt/live ]]; then
  log "Requesting Let's Encrypt cert for ${DOMAIN}..."
  certbot --nginx --non-interactive --agree-tos -m "${AINDGC_ADMIN_EMAIL}" \
    -d "${DOMAIN}" -d "www.${DOMAIN}" -d "${ADMIN_DOMAIN}" -d "${API_DOMAIN}" \
    || err "Certbot failed — site will still serve over HTTP until certificate is obtained"
  ok "HTTPS provisioned"
else
  log "Cert already exists, skipping certbot"
fi

# ---- 9. Verify ----
log "Final smoke test..."
sleep 5
curl -fsI https://${DOMAIN} >/dev/null && ok "Frontend: https://${DOMAIN}" || err "Frontend HTTPS failed"
curl -fs https://${DOMAIN}/api/health >/dev/null && ok "Backend: https://${DOMAIN}/api/health" || err "Backend health failed"

log "=========================================================="
log "  Deploy complete."
log "  Site:   https://${DOMAIN}"
log "  Admin:  https://${ADMIN_DOMAIN}"
log "  API:    https://${DOMAIN}/api/health"
log "=========================================================="
