// Convert the Aindgc MySQL 8 schema into an H2-compatible schema.
//
// H2 differences this handles:
//   1. "SET NAMES utf8mb4" / "SET FOREIGN_KEY_CHECKS" are not valid H2 -> dropped.
//   2. Inline "KEY x (cols)" / "UNIQUE KEY x (cols)" are not valid inside CREATE TABLE
//      in H2 -> hoisted out into standalone CREATE [UNIQUE] INDEX statements.
//   3. Index names are SCHEMA-GLOBAL in H2 but PER-TABLE in MySQL. This schema reuses
//      names like uk_share and idx_user across several tables, so every index is
//      renamed to <table>_<name> to avoid "index name already exists".
//   4. BIGINT UNSIGNED AUTO_INCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
//   5. "ON UPDATE CURRENT_TIMESTAMP" is unsupported in H2. Dropped on purpose: the
//      MetaObjectHandler already stamps updated_at on every update, so behaviour is kept.
//   6. JSON -> CLOB. The app maps those columns to String; H2's native JSON type adds
//      parsing strictness with no benefit here.
//   7. Inline column COMMENT '...' -> dropped (H2 wants COMMENT ON COLUMN).
//   8. Column names that collide with H2 reserved words get quoted.
//
// Usage: node mysql2h2.mjs <schema-in> <schema-out> [seed-in] [seed-out]
import { readFileSync, writeFileSync } from 'node:fs'

const [, , inPath, outPath, seedIn, seedOut] = process.argv
if (!inPath || !outPath) {
  console.error('usage: node mysql2h2.mjs <schema-in.sql> <schema-out.sql> [seed-in.sql] [seed-out.sql]')
  process.exit(1)
}

// H2 reserved words that plausibly appear as column names in this schema.
const RESERVED = new Set([
  'LIMIT', 'OFFSET', 'KEY', 'VALUE', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND',
  'CHECK', 'USER', 'GROUP', 'ORDER', 'ROW', 'ROWS', 'CURRENT_DATE', 'CURRENT_TIME',
  'CURRENT_TIMESTAMP', 'SESSION_USER', 'SYSTEM_USER', 'ARRAY', 'INTERVAL', 'TOP', 'FETCH'
])

// Key columns the app resolves rows by — matched case-insensitively on MySQL.
const CASE_INSENSITIVE_COLS = new Set(['slug', 'code', 'page_key', 'config_key'])

const raw = readFileSync(inPath, 'utf8')
const out = []
const warn = []

// ---- 1. strip session-level MySQL statements ----
let sql = raw
  .replace(/^\s*SET\s+NAMES\s+\w+\s*;?\s*$/gim, '')
  .replace(/^\s*SET\s+FOREIGN_KEY_CHECKS\s*=\s*\d+\s*;?\s*$/gim, '')
  // Drop the original MySQL banner: it would claim "Schema (MySQL 8.0)" in an H2 file.
  .replace(/^-- =+\r?\n-- Aindgc · Schema \(MySQL 8\.0\)[\s\S]*?^-- =+\r?\n/gim, '')
  // Drop the hand-written DROP TABLE lines; each CREATE below emits its own
  // "DROP TABLE IF EXISTS <t> CASCADE" immediately before it, which also handles
  // inter-table dependencies correctly.
  .replace(/^\s*DROP\s+TABLE\s+IF\s+EXISTS\s+\w+\s*;\s*$/gim, '')

// ---- 2. rewrite every CREATE TABLE block ----
const tableRe = /CREATE\s+TABLE\s+`?(\w+)`?\s*\(([\s\S]*?)\n\)\s*ENGINE=[^;]*;/gi
let m
let tableCount = 0
let indexCount = 0

sql = sql.replace(tableRe, (_full, table, body) => {
  tableCount++
  const lines = body.split('\n')
  const cols = []
  const indexes = []

  for (const lineRaw of lines) {
    const line = lineRaw.trim()
    if (!line) continue

    // PRIMARY KEY stays inline.
    if (/^PRIMARY\s+KEY\s*\(/i.test(line)) {
      cols.push(line.replace(/,$/, ''))
      continue
    }

    // Hoist indexes out of the table body.
    const idx = line.match(/^(UNIQUE\s+)?KEY\s+`?(\w+)`?\s*\(([^)]*)\)\s*,?$/i)
    if (idx) {
      const isUnique = !!idx[1]
      const rawName = idx[2]
      const colList = idx[3]
      // MySQL index names are per-table; H2's are global -> namespace by table.
      const name = `${table}_${rawName}`
      indexes.push(`CREATE ${isUnique ? 'UNIQUE ' : ''}INDEX IF NOT EXISTS ${name} ON ${table} (${colList});`)
      indexCount++
      continue
    }

    // Foreign keys are kept inline; this schema declares none, but be explicit.
    if (/^(CONSTRAINT|FOREIGN\s+KEY|CHECK)\b/i.test(line)) {
      cols.push(line.replace(/,$/, ''))
      continue
    }

    // ---- column definition ----
    let c = line.replace(/,$/, '')

    // Drop inline column COMMENT '...'
    c = c.replace(/\s+COMMENT\s+'[^']*'/i, '')
    // Drop ON UPDATE CURRENT_TIMESTAMP (MetaObjectHandler covers it)
    c = c.replace(/\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP/i, '')
    // JSON -> CLOB
    c = c.replace(/\bJSON\b/gi, 'CLOB')
    // MySQL text types -> CLOB (H2 2.x has no MEDIUMTEXT / TEXT).
    // \bTEXT\b cannot match inside MEDIUMTEXT, so order is not load-bearing.
    c = c.replace(/\bMEDIUMTEXT\b/gi, 'CLOB')
    c = c.replace(/\bLONGTEXT\b/gi, 'CLOB')
    c = c.replace(/\bTEXT\b/gi, 'CLOB')
    // BIGINT UNSIGNED AUTO_INCREMENT -> identity
    c = c.replace(/\bBIGINT\s+UNSIGNED\s+NOT\s+NULL\s+AUTO_INCREMENT\b/i,
      'BIGINT GENERATED BY DEFAULT AS IDENTITY')
    // remaining UNSIGNED
    c = c.replace(/\bBIGINT\s+UNSIGNED\b/gi, 'BIGINT')
    c = c.replace(/\bINT\s+UNSIGNED\b/gi, 'INT')
    c = c.replace(/\bSMALLINT\s+UNSIGNED\b/gi, 'SMALLINT')

    // Quote reserved-word column names.
    const nameMatch = c.match(/^`?(\w+)`?\s/)
    if (nameMatch) {
      const colName = nameMatch[1]
      if (RESERVED.has(colName.toUpperCase())) {
        warn.push(`${table}.${colName} is an H2 reserved word -> quoted`)
        c = '`' + colName + '`' + c.slice(nameMatch[0].length - 1).replace(/^`?\w+`?\s/, '')
        c = c.replace(/^`(\w+)`/, '`$1`')
      } else if (CASE_INSENSITIVE_COLS.has(colName)) {
        // MySQL's default utf8mb4_unicode_ci compares strings case-insensitively.
        // H2 compares case-sensitively, so a lookup like selectBySlug("Workflow")
        // would silently miss on H2 while working on MySQL. H2 2.x exposes this as a
        // distinct type — "VARCHAR(n) IGNORECASE" is a syntax error.
        // The line starts with the column name, so the type is not at position 0.
        const before = c
        c = c.replace(/\bVARCHAR\((\d+)\)/i, 'VARCHAR_IGNORECASE($1)')
        if (c === before) warn.push(`${table}.${colName} is a key column but not VARCHAR — left case-sensitive`)
      }
    }

    cols.push(c)
  }

  const bodyOut = cols.map((c) => '    ' + c).join(',\n')
  // Deliberately no "DROP TABLE" here: this script is applied by Spring Boot on EVERY
  // boot (spring.sql.init.mode=always), so a DROP would wipe production data on restart.
  // CREATE TABLE IF NOT EXISTS is a no-op once the table exists. Use --reset for a wipe.
  const tail = `CREATE TABLE IF NOT EXISTS ${table} (\n${bodyOut}\n);`
  return indexes.length
    ? [tail, ...indexes].join('\n')
    : tail
})

// ---- 3. prepend a header ----
const header = `-- =====================================================================
-- Aindgc · Schema (H2)
--
-- AUTO-GENERATED from 01-schema.sql (MySQL 8) by deploy/docker/tools/mysql2h2.mjs
-- Do not hand-edit: regenerate instead, or the two schemas will drift.
--
-- Differences vs the MySQL original, all intentional:
--   * inline KEY / UNIQUE KEY hoisted into standalone CREATE INDEX
--   * index names prefixed with the table name (H2 index names are schema-global,
--     MySQL's are per-table, and this schema reused uk_share / idx_user everywhere)
--   * BIGINT UNSIGNED AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--   * JSON -> CLOB (mapped to String by the app; avoids H2 JSON parse strictness)
--   * MEDIUMTEXT / TEXT -> CLOB (H2 2.x has neither type)
--   * ON UPDATE CURRENT_TIMESTAMP dropped — MybatisPlusMetaObjectHandler stamps
--     updated_at on every update, so the behaviour is preserved
--   * inline column COMMENT dropped (H2 uses COMMENT ON COLUMN)
-- =====================================================================

`

const result = header + sql.trimStart().replace(/\n{3,}/g, '\n\n') + '\n'
writeFileSync(outPath, result, 'utf8')
console.log(`converted ${tableCount} tables, hoisted ${indexCount} indexes`)

// =====================================================================
// Phase 2: seed file — "INSERT IGNORE" -> H2 "MERGE ... KEY (...)"
// =====================================================================
// INSERT IGNORE silently skips conflicting rows; MySQL makes that safe on re-run.
// H2 has no IGNORE, so we use MERGE, which is an upsert keyed on the table's
// unique constraint. The key column per table was read off the MySQL schema.
const SEED_KEYS = {
  t_tool_category: 'slug',
  t_seo_page: 'page_key',
  t_site_config: 'config_key',
  t_ad_slot: 'code'
}

if (seedIn) {
  const seed = readFileSync(seedIn, 'utf8')
  // NOTE: do NOT name this `seedOut` — that is the output *path* parameter.
  const seedSql = seed
    .replace(/^-- =+\r?\n-- Aindgc · Seed data[\s\S]*?^-- =+\r?\n/gim, '')
    .replace(/INSERT\s+IGNORE\s+INTO\s+(\w+)\s*\(([^)]*)\)\s*VALUES/gi,
      (_m, table, cols) => {
        const key = SEED_KEYS[table]
        if (!key) {
          warn.push(`seed: no unique-key mapping for ${table} — left INSERT IGNORE as-is`)
          return `INSERT INTO ${table} (${cols}) VALUES`
        }
        return `MERGE INTO ${table} (${cols}) KEY (${key}) VALUES`
      })
    // MySQL escapes an embedded quote as \' ; SQL standard doubles it.
    .replace(/\\'/g, "''")

  const seedHeader = `-- =====================================================================
-- Aindgc · Seed data (H2)
--
-- AUTO-GENERATED from 02-seed.sql by deploy/docker/tools/mysql2h2.mjs
--
-- "INSERT IGNORE" became "MERGE ... KEY (...)": MySQL's IGNORE silently skips
-- conflicting rows, H2 has no equivalent, and MERGE is the idempotent upsert
-- that keeps re-running this file on every boot safe.
-- =====================================================================

`
  writeFileSync(seedOut, seedHeader + seedSql, 'utf8')
  const merges = (seedSql.match(/MERGE INTO/gi) || []).length
  const left = (seedSql.match(/INSERT\s+IGNORE/gi) || []).length
  console.log(`converted ${merges} seed statements to MERGE (${left} INSERT IGNORE left behind)`)
}

if (warn.length) {
  console.log('warnings:')
  for (const w of warn) console.log('  - ' + w)
}
