package com.aindgc.ai.generator;

import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;
import java.util.regex.Pattern;

@Service
public class AgentSkillGenerator {

    private static final Map<String, String> TARGET_LABEL = Map.of(
        "CLAUDE_CODE", "Claude Code",
        "CODEX", "Codex CLI",
        "CURSOR", "Cursor",
        "GEMINI_CLI", "Gemini CLI",
        "ALL", "Universal"
    );

    public GeneratorResult generate(Map<String, Object> input) {
        String name = str(input, "name", "Untitled Skill");
        String role = str(input, "role", "");
        String purpose = str(input, "purpose", "");
        String instructions = str(input, "instructions", "");
        String target = str(input, "target", "CLAUDE_CODE");
        @SuppressWarnings("unchecked")
        List<String> tools = listStr(input, "tools");
        String workflow = str(input, "workflow", "");
        String examples = str(input, "examples", "");
        String constraints = str(input, "constraints", "");

        String slug = slugify(name);
        String date = LocalDate.now().toString();
        String targetLabel = TARGET_LABEL.getOrDefault(target, target);
        String purposeEscaped = purpose.replace("\"", "\\\"");

        StringBuilder md = new StringBuilder();
        md.append("---\n");
        md.append("name: ").append(name).append("\n");
        md.append("description: ");
        if (purposeEscaped.length() > 160) md.append(purposeEscaped, 0, 160);
        else md.append(purposeEscaped);
        md.append("\n");
        md.append("target: ").append(targetLabel).append("\n");
        md.append("version: 0.1.0\n");
        md.append("created: ").append(date).append("\n");
        md.append("tags: [agent, skill, aindgc]\n");
        md.append("---\n\n");
        md.append("# ").append(name).append("\n\n");
        if (!role.isEmpty()) md.append("## Role\n\n").append(role).append("\n\n");
        if (!purpose.isEmpty()) md.append("## Purpose\n\n").append(purpose).append("\n\n");
        md.append("## Instructions\n\n").append(instructions.isEmpty() ? "_Define clear, actionable instructions for the agent._" : instructions).append("\n\n");
        if (!tools.isEmpty()) {
            md.append("## Tools\n\n");
            for (String t : tools) md.append("- **").append(t).append("**\n");
            md.append("\n");
        }
        if (!workflow.isEmpty()) md.append("## Workflow\n\n").append(workflow).append("\n\n");
        if (!examples.isEmpty()) md.append("## Examples\n\n").append(examples).append("\n\n");
        if (!constraints.isEmpty()) md.append("## Constraints\n\n").append(constraints).append("\n\n");
        md.append("---\n*Generated by Aindgc Agent Skills Generator. Compatible with ").append(targetLabel).append(".*");

        Map<String, Object> json = new LinkedHashMap<>();
        json.put("schema", "aindgc.skill/v1");
        json.put("target", target);
        json.put("name", name);
        json.put("slug", slug);
        json.put("role", role);
        json.put("purpose", purpose);
        json.put("instructions", instructions);
        json.put("tools", tools);
        json.put("workflow", workflow);
        json.put("examples", examples);
        json.put("constraints", constraints);
        json.put("created_at", new Date().toString());

        return new GeneratorResult(md.toString(), json);
    }

    static String slugify(String s) {
        if (s == null) return "";
        String r = s.toLowerCase().trim();
        r = Pattern.compile("[^a-z0-9]+").matcher(r).replaceAll("-");
        return r.replaceAll("(^-+)|(-+$)", "");
    }

    static String str(Map<String, Object> m, String k, String d) {
        if (m == null) return d;
        Object v = m.get(k);
        return v == null ? d : v.toString();
    }

    @SuppressWarnings("unchecked")
    static List<String> listStr(Map<String, Object> m, String k) {
        if (m == null) return List.of();
        Object v = m.get(k);
        if (v instanceof List) return (List<String>) v;
        if (v == null) return List.of();
        return List.of(v.toString());
    }
}
