package com.aindgc.ai.generator;

import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;

@Service
public class AgentWorkflowGenerator {

    public GeneratorResult generate(Map<String, Object> input) {
        String name = str(input, "name", "Untitled Workflow");
        String goal = str(input, "goal", "_Define the goal of this workflow._");
        String audience = str(input, "audience", "");
        @SuppressWarnings("unchecked")
        List<String> triggers = listStr(input, "triggers");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> steps = listMap(input, "steps");
        @SuppressWarnings("unchecked")
        List<String> tools = listStr(input, "tools");
        @SuppressWarnings("unchecked")
        List<String> success = listStr(input, "successCriteria");
        String outputFormat = str(input, "outputFormat", "");
        String date = LocalDate.now().toString();

        StringBuilder md = new StringBuilder();
        md.append("# ").append(name).append("\n\n");
        md.append("> Generated by Aindgc · ").append(date).append("\n\n");
        md.append("## Goal\n\n").append(goal).append("\n\n");
        if (!audience.isEmpty()) {
            md.append("**Audience**: ").append(audience).append("\n\n");
        }
        if (!triggers.isEmpty()) {
            md.append("## Triggers\n\n");
            for (String t : triggers) md.append("- ").append(t).append("\n");
            md.append("\n");
        }
        if (!steps.isEmpty()) {
            md.append("## Steps\n\n");
            for (int i = 0; i < steps.size(); i++) {
                Map<String, Object> s = steps.get(i);
                String sName = str(s, "name", "Step");
                String sType = str(s, "type", "ai");
                String sDesc = str(s, "description", "_Describe what this step does._");
                md.append("### ").append(String.format("%02d", i + 1)).append(". ")
                        .append(sName).append(" `").append(sType).append("`\n\n")
                        .append(sDesc).append("\n\n");
            }
        }
        if (!tools.isEmpty()) {
            md.append("## Tools\n\n");
            for (String t : tools) md.append("- ").append(t).append("\n");
            md.append("\n");
        }
        if (!success.isEmpty()) {
            md.append("## Success Criteria\n\n");
            for (String c : success) md.append("- [ ] ").append(c).append("\n");
            md.append("\n");
        }
        if (!outputFormat.isEmpty()) {
            md.append("## Output Format\n\n```json\n").append(outputFormat).append("\n```\n\n");
        }
        md.append("---\n_This workflow was generated by Aindgc Agent Workflow Generator._");

        Map<String, Object> json = new LinkedHashMap<>();
        json.put("schema", "aindgc.workflow/v1");
        json.put("generated_at", new Date().toString());
        json.put("name", name);
        json.put("goal", goal);
        json.put("audience", audience);
        json.put("triggers", triggers);
        List<Map<String, Object>> stepsJson = new ArrayList<>();
        for (int i = 0; i < steps.size(); i++) {
            Map<String, Object> s = steps.get(i);
            Map<String, Object> sj = new LinkedHashMap<>();
            sj.put("order", i + 1);
            sj.put("id", str(s, "id", ""));
            sj.put("name", str(s, "name", ""));
            sj.put("type", str(s, "type", ""));
            sj.put("description", str(s, "description", ""));
            stepsJson.add(sj);
        }
        json.put("steps", stepsJson);
        json.put("tools", tools);
        json.put("success_criteria", success);
        json.put("output_format", outputFormat.isEmpty() ? null : safeParse(outputFormat));

        return new GeneratorResult(md.toString(), json);
    }

    static String str(Map<String, Object> m, String key, String def) {
        Object v = m == null ? null : m.get(key);
        return v == null ? def : v.toString();
    }

    @SuppressWarnings("unchecked")
    static List<String> listStr(Map<String, Object> m, String key) {
        Object v = m == null ? null : m.get(key);
        if (v == null) return List.of();
        if (v instanceof List) return (List<String>) v;
        return List.of(v.toString());
    }

    @SuppressWarnings("unchecked")
    static List<Map<String, Object>> listMap(Map<String, Object> m, String key) {
        Object v = m == null ? null : m.get(key);
        if (v == null) return List.of();
        if (v instanceof List) return (List<Map<String, Object>>) v;
        return List.of();
    }

    static Object safeParse(String s) {
        try { return new com.fasterxml.jackson.databind.ObjectMapper().readTree(s); }
        catch (Exception e) { return s; }
    }
}
