package com.aindgc.ai.generator;

import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;
import java.util.regex.Pattern;

@Service
public class CodingProjectGenerator {

    private static final Map<String, String> TARGET_FILE = Map.of(
        "CLAUDE_CODE", "CLAUDE.md",
        "CODEX", "AGENTS.md",
        "CURSOR", ".cursorrules",
        "GEMINI_CLI", "GEMINI.md"
    );

    private static final Map<String, String> TARGET_LABEL = Map.of(
        "CLAUDE_CODE", "Claude Code",
        "CODEX", "Codex CLI",
        "CURSOR", "Cursor",
        "GEMINI_CLI", "Gemini CLI"
    );

    public List<Map<String, String>> generateFiles(Map<String, Object> input) {
        String projectName = str(input, "projectName", "My Project");
        String description = str(input, "description", "_Short description of the project._");
        String frontend = str(input, "frontend", "");
        String backend = str(input, "backend", "");
        Boolean fullStack = (Boolean) input.getOrDefault("fullStack", true);
        String aiTarget = str(input, "aiTarget", "CLAUDE_CODE");
        @SuppressWarnings("unchecked")
        List<String> features = listStr(input, "features");
        String conventions = str(input, "conventions", "");
        String slug = slugify(projectName);
        String date = LocalDate.now().toString();
        String aiFileName = TARGET_FILE.getOrDefault(aiTarget, "AGENTS.md");
        String targetLabel = TARGET_LABEL.getOrDefault(aiTarget, aiTarget);

        List<String> stack = new ArrayList<>();
        if (!frontend.isEmpty()) stack.add(frontend);
        if (!backend.isEmpty()) stack.add(backend);
        String stackLine = stack.isEmpty() ? "TBD" : String.join(" + ", stack);

        List<Map<String, String>> files = new ArrayList<>();

        // README.md
        StringBuilder readme = new StringBuilder();
        readme.append("# ").append(projectName).append("\n\n");
        readme.append("> ").append(description).append("\n\n");
        readme.append("**Stack**: ").append(stackLine).append("\n\n");
        readme.append("**AI Coding target**: ").append(targetLabel).append("\n\n");
        readme.append("**Created**: ").append(date).append(" · generated by Aindgc\n\n");
        readme.append("## Quick start\n\n");
        if (!frontend.isEmpty()) readme.append("```bash\ncd frontend && pnpm install && pnpm dev\n```\n\n");
        if (!backend.isEmpty()) readme.append("```bash\ncd backend && ./mvnw spring-boot:run\n```\n\n");
        readme.append("## Features\n\n");
        if (features.isEmpty()) readme.append("_Add features here._\n");
        else for (String f : features) readme.append("- ").append(f).append("\n");
        readme.append("\n## Project layout\n\nSee ARCHITECTURE.md.\n\n## Contributing\n\nSee CONTRIBUTING.md.\n");
        files.add(Map.of("name", "README.md", "content", readme.toString()));

        // ARCHITECTURE.md
        StringBuilder arch = new StringBuilder();
        arch.append("# Architecture\n\n> How the pieces fit together.\n\n## High level\n\n```\n");
        if (!frontend.isEmpty() && !backend.isEmpty()) {
            arch.append("[Browser]\n   ↓\n[Frontend — ").append(frontend).append("]\n   ↓ HTTP/JSON\n[Backend — ").append(backend).append("]\n   ↓\n[Database]\n");
        } else if (!frontend.isEmpty()) {
            arch.append("[Browser]\n   ↓\n[Frontend — ").append(frontend).append("]\n");
        } else if (!backend.isEmpty()) {
            arch.append("[Client]\n   ↓\n[Backend — ").append(backend).append("]\n   ↓\n[Database]\n");
        } else {
            arch.append("_Define the architecture._\n");
        }
        arch.append("```\n\n## Directory layout\n\n```\n").append(slug).append("/\n");
        if (!frontend.isEmpty()) {
            arch.append("├── frontend/        # ").append(frontend).append("\n");
            arch.append("│   ├── src/\n│   ├── public/\n│   ├── package.json\n│   └── README.md\n");
        }
        if (!backend.isEmpty()) {
            arch.append("├── backend/         # ").append(backend).append("\n");
            arch.append("│   ├── src/\n│   ├── pom.xml / package.json / pyproject.toml\n│   └── README.md\n");
        }
        arch.append("├── docs/\n├── tests/\n├── ").append(aiFileName).append("        # AI agent instructions\n");
        arch.append("├── README.md\n└── ARCHITECTURE.md\n```\n\n## Conventions\n\n").append(conventions.isEmpty() ? "_Document conventions as they emerge._" : conventions).append("\n");
        files.add(Map.of("name", "ARCHITECTURE.md", "content", arch.toString()));

        // AI agent instructions
        StringBuilder aiDoc = new StringBuilder();
        aiDoc.append("# AI Agent Instructions\n\n> Read this before making changes. Generated for ").append(targetLabel).append(".\n\n");
        aiDoc.append("## Project\n\n**").append(projectName).append("** — ").append(description).append("\n\n");
        aiDoc.append("**Stack**: ").append(stackLine).append("\n\n");
        aiDoc.append("## Working principles\n\n");
        aiDoc.append("1. **Read before write.** Always read the relevant files first.\n");
        aiDoc.append("2. **Stay consistent.** Match existing code style, naming, and patterns.\n");
        aiDoc.append("3. **Small steps.** Make focused, reviewable changes.\n");
        aiDoc.append("4. **Verify.** Run tests / type-check / build after changes.\n");
        aiDoc.append("5. **No scope creep.** If a task implies larger changes, ask first.\n\n");
        aiDoc.append("## Directory boundaries\n\n");
        if (!frontend.isEmpty()) aiDoc.append("- `frontend/` — ").append(frontend).append(" code only. Don't add backend code here.\n");
        if (!backend.isEmpty()) aiDoc.append("- `backend/` — ").append(backend).append(" code only.\n");
        aiDoc.append("- `docs/` — design notes, decisions, RFCs.\n- `tests/` — end-to-end / integration tests.\n\n");
        aiDoc.append("## Conventions\n\n").append(conventions.isEmpty() ? "_Add team conventions._" : conventions).append("\n\n");
        aiDoc.append("## Features (current scope)\n\n");
        if (features.isEmpty()) aiDoc.append("_List the features currently in scope._\n");
        else for (String f : features) aiDoc.append("- ").append(f).append("\n");
        aiDoc.append("\n## Done when\n\n- [ ] Code matches existing style\n- [ ] No new lint / type errors\n- [ ] Tests pass (or new tests added for new behavior)\n- [ ] CHANGELOG / commit message describes the change\n");
        files.add(Map.of("name", aiFileName, "content", aiDoc.toString()));

        // CONTRIBUTING.md
        String contrib = "# Contributing\n\n## Workflow\n\n1. Branch from `main`.\n2. Make focused commits.\n3. Open a PR with a clear description.\n\n## Commit style\n\nUse Conventional Commits: `feat:`, `fix:`, `docs:`, `refactor:`, `test:`, `chore:`.\n\n## Code style\n\n- Match the existing patterns in each directory.\n- Keep changes minimal — don't refactor unrelated code.\n- Prefer explicit over clever.\n\n## Reporting issues\n\nInclude: expected vs actual, reproduction steps, environment.\n";
        files.add(Map.of("name", "CONTRIBUTING.md", "content", contrib));

        // CHANGELOG.md
        String chlog = "# Changelog\n\n## [Unreleased]\n\n### Added\n- Initial project scaffold generated by Aindgc.\n\n### Notes\n- Stack: " + stackLine + "\n- AI target: " + targetLabel + "\n";
        files.add(Map.of("name", "CHANGELOG.md", "content", chlog));

        return files;
    }

    static String str(Map<String, Object> m, String k, String d) {
        if (m == null) return d;
        Object v = m.get(k);
        return v == null ? d : v.toString();
    }

    @SuppressWarnings("unchecked")
    static List<String> listStr(Map<String, Object> m, String k) {
        if (m == null) return List.of();
        Object v = m.get(k);
        if (v instanceof List) return (List<String>) v;
        if (v == null) return List.of();
        return List.of(v.toString());
    }

    static String slugify(String s) {
        if (s == null) return "";
        String r = s.toLowerCase().trim();
        r = Pattern.compile("[^a-z0-9]+").matcher(r).replaceAll("-");
        return r.replaceAll("(^-+)|(-+$)", "");
    }
}
