package com.aindgc.ai.generator;

import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;

@Service
public class ContextBuilderGenerator {

    public GeneratorResult generate(Map<String, Object> input) {
        String date = LocalDate.now().toString();
        String purpose = str(input, "purpose", "");
        String audience = str(input, "audience", "");
        String scope = str(input, "scope", "");
        String keyInfo = str(input, "keyInfo", "");
        String constraints = str(input, "constraints", "");
        String examples = str(input, "examples", "");
        String successSignals = str(input, "successSignals", "");

        StringBuilder md = new StringBuilder();
        md.append("# Context\n\n> Generated by Aindgc · ").append(date).append("\n\n");
        if (!purpose.isEmpty())         md.append("## 1. Purpose\n\n").append(purpose).append("\n\n");
        if (!audience.isEmpty())        md.append("## 2. Audience\n\n").append(audience).append("\n\n");
        if (!scope.isEmpty())           md.append("## 3. Scope\n\n**In scope:**\n\n").append(scope).append("\n\n");
        if (!keyInfo.isEmpty())         md.append("## 4. Key Information\n\n").append(keyInfo).append("\n\n");
        if (!constraints.isEmpty())     md.append("## 5. Constraints\n\n").append(constraints).append("\n\n");
        if (!examples.isEmpty())        md.append("## 6. Examples\n\n").append(examples).append("\n\n");
        if (!successSignals.isEmpty()) md.append("## 7. Success Signals\n\n").append(successSignals).append("\n\n");
        md.append("---\n*This context package is designed to be pasted into any AI agent's system prompt or context window.*");

        Map<String, Object> json = new LinkedHashMap<>();
        json.put("schema", "aindgc.context/v1");
        json.put("generated_at", new Date().toString());
        json.put("purpose", purpose);
        json.put("audience", audience);
        json.put("scope", scope);
        json.put("key_information", keyInfo);
        json.put("constraints", constraints);
        json.put("examples", examples);
        json.put("success_signals", successSignals);

        return new GeneratorResult(md.toString(), json);
    }

    static String str(Map<String, Object> m, String k, String d) {
        if (m == null) return d;
        Object v = m.get(k);
        return v == null ? d : v.toString();
    }
}
