package com.aindgc.ai.generator;

import org.springframework.stereotype.Service;

import java.util.*;
import java.util.regex.Pattern;

@Service
public class OutputSchemaGenerator {

    private static final Set<String> VALID_TYPES = Set.of(
        "string", "number", "integer", "boolean", "array", "object", "null"
    );

    public GeneratorResult generate(Map<String, Object> input) {
        String name = str(input, "name", "Output");
        String description = str(input, "description", "");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> fields = (List<Map<String, Object>>) input.getOrDefault("fields", List.of());

        // JSON Schema
        Map<String, Object> properties = new LinkedHashMap<>();
        List<String> required = new ArrayList<>();
        for (Map<String, Object> f : fields) {
            properties.put(str(f, "name", ""), buildJsonProperty(f));
            if (Boolean.TRUE.equals(f.get("required"))) {
                required.add(str(f, "name", ""));
            }
        }

        Map<String, Object> jsonSchema = new LinkedHashMap<>();
        jsonSchema.put("$schema", "http://json-schema.org/draft-07/schema#");
        jsonSchema.put("$id", "https://aindgc.com/schemas/" + slugify(name) + ".json");
        jsonSchema.put("title", name);
        jsonSchema.put("description", description);
        jsonSchema.put("type", "object");
        jsonSchema.put("properties", properties);
        if (!required.isEmpty()) jsonSchema.put("required", required);
        jsonSchema.put("additionalProperties", false);

        // TypeScript
        StringBuilder ts = new StringBuilder();
        ts.append("/**\n * ").append(name).append("\n");
        if (!description.isEmpty()) ts.append(" * ").append(description).append("\n");
        ts.append(" */\n");
        ts.append("export interface ").append(toPascal(name)).append(" {\n");
        for (Map<String, Object> f : fields) {
            if (f.get("description") != null) {
                ts.append("  /**\n   * ").append(str(f, "description", "").replace("\n", " ")).append("\n   */\n");
            }
            String type = tsType(f);
            String opt = Boolean.TRUE.equals(f.get("required")) ? "" : "?";
            ts.append("  ").append(str(f, "name", "")).append(opt).append(": ").append(type).append(";\n");
        }
        ts.append("}");

        // Markdown doc
        StringBuilder md = new StringBuilder();
        md.append("# ").append(name).append("\n\n");
        if (!description.isEmpty()) md.append(description).append("\n\n");
        md.append("## Fields\n\n| Name | Type | Required | Description |\n|------|------|----------|-------------|\n");
        for (Map<String, Object> f : fields) {
            String fName = str(f, "name", "");
            String typeStr = str(f, "type", "string").toLowerCase();
            if ("array".equals(typeStr) && f.get("itemType") != null) {
                typeStr = str(f, "itemType", "string").toLowerCase() + "[]";
            }
            @SuppressWarnings("unchecked")
            List<String> enums = (List<String>) f.get("enum");
            if (enums != null && !enums.isEmpty()) {
                typeStr = "enum(" + String.join(", ", enums) + ")";
            }
            md.append("| `").append(fName).append("` | ").append(typeStr)
                    .append(" | ").append(Boolean.TRUE.equals(f.get("required")) ? "yes" : "no")
                    .append(" | ").append(str(f, "description", "").replace("|", "\\|")).append(" |\n");
        }
        md.append("\n## JSON Schema\n\n```json\n");
        try {
            md.append(new com.fasterxml.jackson.databind.ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(jsonSchema));
        } catch (Exception e) {
            md.append("{}");
        }
        md.append("\n```\n\n## TypeScript\n\n```ts\n").append(ts).append("\n```\n\n*Generated by Aindgc Output Schema Generator.*");

        return new GeneratorResult(md.toString(), jsonSchema);
    }

    private Map<String, Object> buildJsonProperty(Map<String, Object> f) {
        Map<String, Object> base = new LinkedHashMap<>();
        if (f.get("description") != null) base.put("description", str(f, "description", ""));
        @SuppressWarnings("unchecked")
        List<String> enums = (List<String>) f.get("enum");
        String type = str(f, "type", "string");
        if (enums != null && !enums.isEmpty()) {
            base.put("type", "string");
            base.put("enum", enums);
        } else if ("array".equals(type)) {
            base.put("type", "array");
            Map<String, Object> items = new LinkedHashMap<>();
            items.put("type", str(f, "itemType", "string"));
            base.put("items", items);
        } else {
            base.put("type", VALID_TYPES.contains(type) ? type : "string");
        }
        if (f.get("format") != null) base.put("format", str(f, "format", ""));
        if (f.get("defaultValue") != null && !str(f, "defaultValue", "").isEmpty()) {
            base.put("default", coerce(str(f, "defaultValue", ""), type));
        }
        return base;
    }

    private Object coerce(String v, String type) {
        if ("number".equals(type) || "integer".equals(type)) {
            try { return Double.parseDouble(v); } catch (Exception e) { return v; }
        }
        if ("boolean".equals(type)) return Boolean.parseBoolean(v);
        return v;
    }

    private String tsType(Map<String, Object> f) {
        String type = str(f, "type", "string");
        @SuppressWarnings("unchecked")
        List<String> enums = (List<String>) f.get("enum");
        if (enums != null && !enums.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < enums.size(); i++) {
                if (i > 0) sb.append(" | ");
                sb.append("'").append(enums.get(i)).append("'");
            }
            return sb.toString();
        }
        switch (type) {
            case "string":  return "string";
            case "number":
            case "integer": return "number";
            case "boolean": return "boolean";
            case "null":    return "null";
            case "array":   return (str(f, "itemType", "string")) + "[]";
            case "object":  return "Record<string, unknown>";
            default:        return "unknown";
        }
    }

    static String str(Map<String, Object> m, String k, String d) {
        if (m == null) return d;
        Object v = m.get(k);
        return v == null ? d : v.toString();
    }

    static String slugify(String s) {
        if (s == null) return "";
        String r = s.toLowerCase().trim();
        r = Pattern.compile("[^a-z0-9]+").matcher(r).replaceAll("-");
        return r.replaceAll("(^-+)|(-+$)", "");
    }

    static String toPascal(String s) {
        if (s == null || s.isEmpty()) return "Output";
        StringBuilder sb = new StringBuilder();
        for (String w : s.split("[^a-zA-Z0-9]+")) {
            if (w.isEmpty()) continue;
            sb.append(Character.toUpperCase(w.charAt(0))).append(w.substring(1));
        }
        return sb.length() == 0 ? "Output" : sb.toString();
    }
}
