package com.aindgc.ai.generator;

import org.springframework.stereotype.Service;

import java.util.*;

@Service
public class PromptBuilderGenerator {

    private static final Map<String, String> TONE_DESC = Map.of(
        "formal",    "Use a formal, professional tone. Avoid colloquialisms.",
        "casual",    "Use a casual, approachable tone.",
        "technical", "Use precise technical language. Assume the reader is an expert.",
        "friendly",  "Use a warm, friendly tone. Encourage the reader."
    );

    public GeneratorResult generate(Map<String, Object> input) {
        String task = str(input, "task", "");
        String role = str(input, "role", "");
        String audience = str(input, "audience", "");
        String context = str(input, "context", "");
        String constraints = str(input, "constraints", "");
        String outputFormat = str(input, "outputFormat", "");
        String examples = str(input, "examples", "");
        String tone = str(input, "tone", "formal");
        boolean includeSteps = Boolean.TRUE.equals(input.get("includeSteps"));

        StringBuilder md = new StringBuilder();
        md.append("# Prompt\n\n");
        if (!role.isEmpty())     md.append("## Role\n\nYou are ").append(role).append(".\n\n");
        if (!audience.isEmpty()) md.append("## Audience\n\nYour audience: ").append(audience).append(".\n\n");
        md.append("## Task\n\n").append(task.isEmpty() ? "_Describe the task you want done._" : task).append("\n\n");
        if (!context.isEmpty()) md.append("## Context\n\n").append(context).append("\n\n");
        if (includeSteps) {
            md.append("## Approach\n\nThink through this step by step:\n");
            md.append("1. Understand the request and identify unknowns.\n");
            md.append("2. Lay out the structure of your answer.\n");
            md.append("3. Fill in each section.\n");
            md.append("4. Self-review against constraints before responding.\n\n");
        }
        if (!constraints.isEmpty()) md.append("## Constraints\n\n").append(constraints).append("\n\n");
        md.append("## Tone\n\n").append(TONE_DESC.getOrDefault(tone, TONE_DESC.get("formal"))).append("\n\n");
        if (!outputFormat.isEmpty()) md.append("## Output format\n\n").append(outputFormat).append("\n\n");
        if (!examples.isEmpty()) md.append("## Examples\n\n").append(examples).append("\n\n");
        md.append("---\n*Generated by Aindgc Prompt Structure Builder.*");

        Map<String, Object> json = new LinkedHashMap<>();
        json.put("schema", "aindgc.prompt/v1");
        json.put("role", role);
        json.put("audience", audience);
        json.put("task", task);
        json.put("context", context);
        json.put("constraints", constraints);
        json.put("output_format", outputFormat);
        json.put("examples", examples);
        json.put("tone", tone);
        json.put("include_steps", includeSteps);

        return new GeneratorResult(md.toString(), json);
    }

    static String str(Map<String, Object> m, String k, String d) {
        if (m == null) return d;
        Object v = m.get(k);
        return v == null ? d : v.toString();
    }
}
