/**
 * Workflow Pinia store
 * - Holds the current working graph (graph being edited)
 * - Persists saved workflows to localStorage (Phase 14: server)
 * - Exports Markdown / JSON
 */
import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import type { WorkflowGraph, WorkflowNodeData, NodeKind, WorkflowTemplate } from '@utils/workflowTypes'
import { NODE_KINDS } from '@utils/workflowTypes'
import { useLocalStorage } from '@composables/useLocalStorage'

const STORAGE_KEY = 'aindgc_workflows_v1'

function emptyGraph(): WorkflowGraph {
  const id = `wf-${Date.now().toString(36)}`
  const now = Date.now()
  return {
    id,
    name: 'Untitled Workflow',
    description: '',
    nodes: [],
    edges: [],
    createdAt: now,
    updatedAt: now
  }
}

export const useWorkflowStore = defineStore('workflow', () => {
  const current = ref<WorkflowGraph>(emptyGraph())
  const saved = useLocalStorage<WorkflowGraph[]>(STORAGE_KEY, [])

  const selectedNodeId = ref<string | null>(null)
  const selectedNode = computed(() =>
    current.value.nodes.find(n => n.id === selectedNodeId.value) || null
  )

  function reset() {
    current.value = emptyGraph()
    selectedNodeId.value = null
  }

  function loadGraph(g: WorkflowGraph) {
    current.value = JSON.parse(JSON.stringify(g))
    selectedNodeId.value = null
  }

  function loadTemplate(t: WorkflowTemplate) {
    const id = `wf-${Date.now().toString(36)}`
    current.value = {
      ...JSON.parse(JSON.stringify(t.graph)),
      id,
      name: `${t.name} (copy)`,
      createdAt: Date.now(),
      updatedAt: Date.now()
    }
    selectedNodeId.value = null
  }

  function addNode(kind: NodeKind, position: { x: number; y: number }) {
    const id = `n-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`
    const meta = NODE_KINDS[kind]
    current.value.nodes.push({
      id,
      type: kind,
      position,
      data: {
        kind,
        config: {
          label: meta.label,
          description: meta.description
        }
      }
    })
    selectedNodeId.value = id
    touch()
  }

  function updateNode(id: string, patch: Partial<{ position: { x: number; y: number }; data: WorkflowNodeData }>) {
    const node = current.value.nodes.find(n => n.id === id)
    if (!node) return
    if (patch.position) node.position = patch.position
    if (patch.data) node.data = patch.data
    touch()
  }

  function removeNode(id: string) {
    current.value.nodes = current.value.nodes.filter(n => n.id !== id)
    current.value.edges = current.value.edges.filter(e => e.source !== id && e.target !== id)
    if (selectedNodeId.value === id) selectedNodeId.value = null
    touch()
  }

  function updateEdge(id: string, patch: Partial<{ data: { branch?: 'always' | 'onSuccess' | 'onError' } }>) {
    const edge = current.value.edges.find(e => e.id === id)
    if (!edge) return
    if (patch.data) edge.data = { ...(edge.data || {}), ...patch.data }
    touch()
  }

  function removeEdge(id: string) {
    current.value.edges = current.value.edges.filter(e => e.id !== id)
    touch()
  }

  function renameGraph(name: string) {
    current.value.name = name
    touch()
  }

  function setDescription(desc: string) {
    current.value.description = desc
    touch()
  }

  function touch() {
    current.value.updatedAt = Date.now()
  }

  function saveCurrent() {
    const idx = saved.value.findIndex(s => s.id === current.value.id)
    const snapshot = JSON.parse(JSON.stringify(current.value)) as WorkflowGraph
    if (idx >= 0) saved.value.splice(idx, 1, snapshot)
    else saved.value.unshift(snapshot)
  }

  function deleteSaved(id: string) {
    saved.value = saved.value.filter(s => s.id !== id)
  }

  function exportJSON(): string {
    return JSON.stringify(current.value, null, 2)
  }

  function exportMarkdown(): string {
    const g = current.value
    const md: string[] = []
    md.push(`# ${g.name || 'Untitled Workflow'}`)
    md.push('')
    if (g.description) {
      md.push(g.description)
      md.push('')
    }
    md.push(`> Generated by Aindgc Workflow Builder · ${new Date().toISOString().slice(0, 10)}`)
    md.push('')
    md.push(`## Graph`)
    md.push('')
    md.push(`- **Nodes**: ${g.nodes.length}`)
    md.push(`- **Edges**: ${g.edges.length}`)
    md.push('')
    md.push(`## Nodes`)
    md.push('')
    if (!g.nodes.length) {
      md.push('_No nodes._')
    } else {
      g.nodes.forEach((n, i) => {
        const meta = NODE_KINDS[n.data.kind]
        md.push(`### ${String(i + 1).padStart(2, '0')}. ${n.data.config.label || meta.label} \`${n.data.kind}\``)
        if (n.data.config.description) {
          md.push('')
          md.push(n.data.config.description)
        }
        if (n.data.config.payload && Object.keys(n.data.config.payload).length) {
          md.push('')
          md.push('```json')
          md.push(JSON.stringify(n.data.config.payload, null, 2))
          md.push('```')
        }
        md.push('')
      })
    }
    md.push(`## Edges`)
    md.push('')
    if (!g.edges.length) {
      md.push('_No edges._')
    } else {
      g.edges.forEach(e => {
        const src = g.nodes.find(n => n.id === e.source)
        const tgt = g.nodes.find(n => n.id === e.target)
        const branch = e.data?.branch && e.data.branch !== 'always' ? ` (${e.data.branch})` : ''
        md.push(`- ${src?.data.config.label || e.source} → ${tgt?.data.config.label || e.target}${branch}`)
      })
    }
    md.push('')
    md.push(`---`)
    md.push(`_This workflow definition is the same JSON used by Aindgc Workflow Generator. Edit, version, and run it with your AI agent._`)
    return md.join('\n')
  }

  return {
    current,
    saved,
    selectedNodeId,
    selectedNode,
    reset,
    loadGraph,
    loadTemplate,
    addNode,
    updateNode,
    removeNode,
    updateEdge,
    removeEdge,
    renameGraph,
    setDescription,
    touch,
    saveCurrent,
    deleteSaved,
    exportJSON,
    exportMarkdown
  }
})
